stages:
  - build
  - deploy

run-build:
  stage: build
  image: gcc
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq && apt-get install -y apt-utils libc6-dev-i386 build-essential lib32z1 lib32ncurses6
    - /builds/stereotech/stefirmware/smoothieware/linux_install
    - /builds/stereotech/stefirmware/smoothieware/BuildShell
    - export PATH="/builds/stereotech/stefirmware/smoothieware/gcc-arm-none-eabi/bin:$PATH"
  script:
    - make clean all
  artifacts:
    paths:
      - LPC1768/
  only:
    - develop

run-deploy:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 cp LPC1768/ s3://${BUCKET_NAME}/smoothieware/stable/ --recursive --debug
  environment:
    name: stable
    url: https://s3.eu-west-3.amazonaws.com/${BUCKET_NAME}/smoothieware/stable
    on_stop: run-clean
  only:
    - develop

run-clean:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/smoothieware/stable/smoothieware-build.zip
  environment:
    name: stable
    action: stop
  when: manual



