before_script:
 - apt-get update -qq && apt-get install -y --force-yes software-properties-common
 - add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
 - apt-get update -qq && apt-get install -y --force-yes gcc-arm-none-eabi

stages:
  - build

run-build:
  stage: build
  script:
    - make clean all