before_script:
 - add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - apt-get update -qq
 - apt-get install -y --force-yes gcc-arm-none-eabi

stages:
  - build

run-build:
  stage: build
  script:
    - make clean all