

before_script:
  - /builds/stereotech/stefirmware/smoothieware/linux_install
  - /builds/stereotech/stefirmware/smoothieware/BuildShell

stages:
  - build

run-build:
  stage: build
  script:
    - make clean all