
before_script:
  - /builds/stereotech/stefirmware/smoothieware/linux_install
  - /builds/stereotech/stefirmware/smoothieware/BuildShell
  - dpkg --add-architecture i386
  - apt-get update 
  - apt-get install ia32-libs

stages:
  - build

run-build:
  stage: build
  script:
    - make clean all