before_script:
 - export DEBIAN_FRONTEND=noninteractive
 - /builds/stereotech/stefirmware/smoothieware/travis_install
 - apt-get update -qq && apt-get install -y apt-utils libc6-dev-i386 build-essential lib32z1 lib32ncurses5
 - /builds/stereotech/stefirmware/smoothieware/BuildShell

stages:
  - build

run-build:
  stage: build
  script:
    - make clean all