stages:
  - build
  - deploy

run-build:
  stage: build
  image: gcc
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq && apt-get install -y apt-utils libc6-dev-i386 build-essential lib32z1 lib32ncurses6
    - /builds/stereotech/stefirmware/smoothieware/linux_install
    - /builds/stereotech/stefirmware/smoothieware/BuildShell
    - export PATH="/builds/stereotech/stefirmware/smoothieware/gcc-arm-none-eabi/bin:$PATH"
  script:
    - make clean all
    - cp -r ConfigSamples/STEBoard/ LPC1768/configs
  artifacts:
    paths:
      - LPC1768/
  only:
    - develop

run-deploy:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - python -m zipfile -c smoothie-build.zip LPC1768/main.bin LPC1768/configs/
    - aws s3 cp smoothie-build.zip s3://${BUCKET_NAME}/smoothieware/stable/
  environment:
    name: stable
    url: http://${BUCKET_NAME}/smoothieware/stable/smoothie-build.zip
    on_stop: run-clean
  only:
    - develop

run-clean:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/smoothieware/stable/smoothie-build.zip
  environment:
    name: stable
    action: stop
  when: manual



